CREATE TABLE CUSTOMERS (
	ID INTEGER NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
  CPF_CNPJ VARCHAR2(14) NOT NULL,
  RG_IE VARCHAR2(14) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(255) NOT NULL,
  HASH VARCHAR2(255),
  LAST_ACCESS TIMESTAMP,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY (ID)
);
